### ISSUE TITLE
Commit 3b3c8abb9635eb3ea078a821a99c9ef29d66dff7 broke bazel build with sandboxing

### ISSUE THREAD

**Issue by damienmg** [google/protobuf#1410]
Reposting from https://github.com/google/protobuf/commit/3b3c8abb9635eb3ea078a821a99c9ef29d66dff7

We are issuing a new release so traging the breakage we see on ci.bazel.io

See http://ci.bazel.io/job/protobuf/136/ (bisected to find the culprit).

The exact log:
```
$ bazel build //:protoc
INFO: Found 1 target...
ERROR: /usr/local/google/home/dmarting/toto/protobuf/BUILD:271:1: Linking of rule '//:protoc' failed: namespace-sandbox failed: error executing command <user_home>/.cache/bazel/_bazel_dmarting/c28d9280fb33934092856a1adca4fe91/protobuf/_bin/namespace-sandbox ... (remaining 13 argument(s) skipped).
bazel-out/local_linux-fastbuild/bin/libprotoc_lib.a(java_generator_factory.pic.o): In function `google::protobuf::compiler::java::ImmutableGeneratorFactory::NewExtensionGenerator(google::protobuf::FieldDescriptor const*) const':
java_generator_factory.cc:(.text+0x265): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::ImmutableExtensionLiteGenerator(google::protobuf::FieldDescriptor const*, google::protobuf::compiler::java::Context*)'
bazel-out/local_linux-fastbuild/bin/libprotoc_lib.a(java_message_lite.pic.o): In function `google::protobuf::compiler::java::ImmutableMessageLiteGenerator::Generate(google::protobuf::io::Printer*)':
java_message_lite.cc:(.text+0x1b82): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::ImmutableExtensionLiteGenerator(google::protobuf::FieldDescriptor const*, google::protobuf::compiler::java::Context*)'
java_message_lite.cc:(.text+0x1b9b): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::Generate(google::protobuf::io::Printer*)'
java_message_lite.cc:(.text+0x1baa): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::~ImmutableExtensionLiteGenerator()'
java_message_lite.cc:(.text+0x1f41): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::~ImmutableExtensionLiteGenerator()'
bazel-out/local_linux-fastbuild/bin/libprotoc_lib.a(java_message_lite.pic.o): In function `google::protobuf::compiler::java::ImmutableMessageLiteGenerator::GenerateExtensionRegistrationCode(google::protobuf::io::Printer*)':
java_message_lite.cc:(.text+0x394e): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::ImmutableExtensionLiteGenerator(google::protobuf::FieldDescriptor const*, google::protobuf::compiler::java::Context*)'
java_message_lite.cc:(.text+0x3961): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::GenerateRegistrationCode(google::protobuf::io::Printer*)'
java_message_lite.cc:(.text+0x396d): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::~ImmutableExtensionLiteGenerator()'
java_message_lite.cc:(.text+0x3a14): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::~ImmutableExtensionLiteGenerator()'
collect2: error: ld returned 1 exit status
Target //:protoc failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 28.883s, Critical Path: 27.78s
```

**Comment by damienmg** [comment]
The commit did not completely fix the build, there is still a C++ error (see http://ci.bazel.io/job/protobuf/143/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/console)

```
ERROR: /home/ci/workspace/protobuf/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/BUILD:429:1: C++ compilation of rule '//:protobuf_test' failed: namespace-sandbox failed: error executing command 
  (cd /home/ci/.cache/bazel/_bazel_ci/de06170185e55a5f5b2f721e17b7afeb/linux-x86_64 && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /home/ci/.cache/bazel/_bazel_ci/de06170185e55a5f5b2f721e17b7afeb/linux-x86_64/_bin/namespace-sandbox @/home/ci/.cache/bazel/_bazel_ci/de06170185e55a5f5b2f721e17b7afeb/linux-x86_64/bazel-sandbox/c57a001c-12a1-4c0c-a5d6-04b09e20d23d-118.params -- /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -iquote external/gmock_archive -iquote bazel-out/local-fastbuild/genfiles/external/gmock_archive -isystem src -isystem bazel-out/local-fastbuild/genfiles/src -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/gmock_archive/gmock-1.7.0 -isystem bazel-out/local-fastbuild/genfiles/external/gmock_archive/gmock-1.7.0 -isystem external/gmock_archive/gmock-1.7.0/gtest -isystem bazel-out/local-fastbuild/genfiles/external/gmock_archive/gmock-1.7.0/gtest -isystem external/gmock_archive/gmock-1.7.0/gtest/include -isystem bazel-out/local-fastbuild/genfiles/external/gmock_archive/gmock-1.7.0/gtest/include -isystem external/gmock_archive/gmock-1.7.0/include -isystem bazel-out/local-fastbuild/genfiles/external/gmock_archive/gmock-1.7.0/include -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare '-Wno-error=unused-function' -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local-fastbuild/bin/_objs/protobuf_test/src/google/protobuf/util/field_mask_util_test.pic.o' -MD -MF bazel-out/local-fastbuild/bin/_objs/protobuf_test/src/google/protobuf/util/field_mask_util_test.pic.d -fPIC -c src/google/protobuf/util/field_mask_util_test.cc -o bazel-out/local-fastbuild/bin/_objs/protobuf_test/src/google/protobuf/util/field_mask_util_test.pic.o).
src/google/protobuf/util/field_mask_util_test.cc: In member function 'virtual void google::protobuf::util::{anonymous}::SnakeCaseCamelCaseTest_RoundTripTest_Test::TestBody()':
src/google/protobuf/util/field_mask_util_test.cc:94:3: error: 'sort' is not a member of 'std'
   std::sort(name.begin(), name.end());
   ^
src/google/protobuf/util/field_mask_util_test.cc:100:12: error: 'next_permutation' is not a member of 'std'
   } while (std::next_permutation(name.begin(), name.end()));
            ^
src/google/protobuf/util/field_mask_util_test.cc:105:3: error: 'sort' is not a member of 'std'
   std::sort(name.begin(), name.end());
   ^
src/google/protobuf/util/field_mask_util_test.cc:111:12: error: 'next_permutation' is not a member of 'std'
   } while (std::next_permutation(name.begin(), name.end()));
            ^

```

**Comment by pherl** [comment]
Let me know if you see any further issues.

**Comment by damienmg** [comment]
I just run a build and it is all good. Thanks!

(btw, you can run a build on our ci at any time by using the login button with your google account and clicking on the play button, we can also set-up a hook so it runs a build on every push of protobuf if you wish).
