### ISSUE TITLE
protobuf 3.3 make check libprotoc.so: undefined reference to well_known_types_js

### ISSUE THREAD

**Issue by linux2014linux** [google/protobuf#4111]
libtool: link: ( cd ".libs" && rm -f "libprotoc.la" && ln -s "../libprotoc.la" "libprotoc.la" )
/bin/bash ../libtool --tag=CXX   --mode=link g++ -std=c++11 -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 
-g -DNDEBUG -pthread  -o protoc google/protobuf/compiler/main.o -lpthread libprotobuf.la libprotoc.la -lz 
libtool: link: g++ -std=c++11 -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -pthread -o .libs/
protoc google/protobuf/compiler/main.o  -lpthread ./.libs/libprotobuf.so ./.libs/libprotoc.so -lz -pthread
./.libs/libprotoc.so: undefined reference to `well_known_types_js'
collect2: error: ld returned 1 exit status
make[1]: *** [protoc] 错误 1                                                                                                    
make[1]:正在离开目录 `/home/ll/download/protobuf-3.3.0/src'
make: *** [check-recursive] 错误 1

**Comment by xfxyjwf** [comment]
It should work now (that we deleted the js_embed binary related to well_knonw_types_js).

**Comment by pkubaj** [comment]
It doesn't work, though.

I'm building 3.5.2 on FreeBSD with GCC7.

```
Making all in src
gmake[3]: Entering directory '/tmp/usr/local/poudriere/ports/default/devel/protobuf/work/protobuf-3.5.2/src'
/bin/sh ../libtool  --tag=CXX   --mode=link g++7 -D_THREAD_SAFE -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare  -O2 -pipe  -DGOOGLE_PROTOBUF_NO_RTTI -I/tmp/usr/local/poudriere/ports/default/devel/protobuf/work/protobuf-3.5.2/src -Wl,-rpath=/usr/local/lib/gcc7  -Wl,-rpath=/usr/local/lib/gcc7 -isystem /usr/local/include  -D_THREAD_SAFE -pthread -Wl,-rpath=/usr/local/lib/gcc7 -L/usr/local/lib/gcc7  -o protoc google/protobuf/compiler/main.o -lpthread libprotobuf.la libprotoc.la -lz -L/usr/local/lib
libtool: link: g++7 -D_THREAD_SAFE -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -pipe -DGOOGLE_PROTOBUF_NO_RTTI -I/tmp/usr/local/poudriere/ports/default/devel/protobuf/work/protobuf-3.5.2/src -Wl,-rpath=/usr/local/lib/gcc7 -Wl,-rpath=/usr/local/lib/gcc7 -isystem /usr/local/include -D_THREAD_SAFE -pthread -Wl,-rpath=/usr/local/lib/gcc7 -o .libs/protoc google/protobuf/compiler/main.o  -L/usr/local/lib/gcc7 ./.libs/libprotobuf.so -L/usr/local/lib ./.libs/libprotoc.so /tmp/usr/local/poudriere/ports/default/devel/protobuf/work/protobuf-3.5.2/src/.libs/libprotobuf.so -lpthread -lz -pthread -Wl,-rpath -Wl,/usr/local/lib
./.libs/libprotoc.so: undefined reference to `well_known_types_js'
```

**Comment by nernst** [comment]
I'm having this same issue trying to build on Ubuntu 14.04 with GCC 7.3.

My build script:

```#!/bin/bash

export CC=/usr/local/bin/gcc
export CXX=/usr/local/bin/g++

make clean

./configure --prefix=/home/shared/3d_party64/protobuf-3.5.1 DIST_LANG=cpp

make -j56 && make install```

**Comment by pkubaj** [comment]
> I'm having this same issue trying to build on Ubuntu 14.04 with GCC 7.3.
> 
> My build script:
> 
> ```
> 
> export CC=/usr/local/bin/gcc
> export CXX=/usr/local/bin/g++
> 
> make clean
> 
> ./configure --prefix=/home/shared/3d_party64/protobuf-3.5.1 DIST_LANG=cpp
> 
> make -j56 && make install
> ```

For me, this patch solved it.
https://svnweb.freebsd.org/ports/head/devel/protobuf/files/patch-src_Makefile.am?view=markup&pathrev=483235

**Comment by nernst** [comment]
I just tried applying that patch, and it made no difference to me. I get
the same linker error.
