### ISSUE TITLE
Cannot import name _message

### ISSUE THREAD

**Issue by debclarifai** [google/protobuf#3207]
Traceback (most recent call last):
  File "download_dataset.py", line 4, in <module>
    from experimental.nand.dataset_from_v2_app import app_to_dataset
  File "/Users/debraji/work/clarifai/experimental/nand/dataset_from_v2_app.py", line 11, in <module>
    from datasets.dataset import dataset_registry, DatasetRegistry
  File "/Users/debraji/work/clarifai/datasets/dataset.py", line 11, in <module>
    from datasets.databatch import DataBatch, DataBatchFiller
  File "/Users/debraji/work/clarifai/datasets/databatch.py", line 10, in <module>
    from proto.utils.common import (DataBatch as DataBatchProto, isheavy, overwrite_field)
  File "/Users/debraji/work/clarifai/proto/utils/common.py", line 21, in <module>
    from proto.spire import spire_pb2
  File "/Users/debraji/work/clarifai/proto/spire/spire_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: cannot import name _message

Getting this error after multiple attempts.

**Comment by debclarifai** [comment]
Working on OS X, Python 2.7
