### ISSUE TITLE
'GOOGLE_PREDICT_FALSE' macro redefined from google-glog

### ISSUE THREAD

**Issue by schroederc** [google/protobuf#208]
In the 3.0.0-alpha-1 include 'google/protobuf/stubs/common.h', the GOOGLE_PREDICT_FALSE macro is defined.  Likewise, in 'glog/logging.h' from https://code.google.com/p/google-glog/, GOOGLE_PREDICT_FALSE is also defined, causing a compilation warning (and error with -Werror).

This currently affects the https://github.com/google/kythe repository when upgrading to 3.0.0-alpha-1.  Full compilation error below:
```
In file included from kythe/cxx/common/index_pack.cc:28:
third_party/glog/include/glog/logging.h:132:9: error: 'GOOGLE_PREDICT_FALSE' macro redefined [-Werror]
#define GOOGLE_PREDICT_FALSE(x) (__builtin_expect(x, 0))
        ^
third_party/protobuf/include/google/protobuf/stubs/common.h:253:9: note: previous definition is here
#define GOOGLE_PREDICT_FALSE(x) (__builtin_expect(!!(x), 1))
        ^
1 error generated.
```

**Comment by schroederc** [comment]
This is mostly an error on glog's part since they don't guard their definitions.
