### ISSUE TITLE
Compile protobuf 3.4.0 with Visual Studio 2017 - can't find pthread.h ?

### ISSUE THREAD

**Issue by NelsonBilber** [google/protobuf#3500]
I run the cmake with new version of protobuf but when click "configure" on cmake GUI  it gives an error. Says it misses pthread.h.
I think pthread.h is for Unix systems ? 
I'm using Visual studio 2017 64 bits

**CMakeError.log**

Determining if the include file pthread.h exists failed with the following output:
Change Dir: E:/tmp/protobuf-3.4.0/cmake/b1/CMakeFiles/CMakeTmp

Run Build Command:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional/MSBuild/15.0/Bin/MSBuild.exe" "cmTC_fb9ee.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=15.0"
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

Build started 16/08/2017 14:13:45.

Project "E:\tmp\protobuf-3.4.0\cmake\b1\CMakeFiles\CMakeTmp\cmTC_fb9ee.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_fb9ee.dir\Debug\".

  Creating directory "E:\tmp\protobuf-3.4.0\cmake\b1\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_fb9ee.dir\Debug\cmTC_fb9ee.tlog\".

InitializeBuildStatus:

  Creating "cmTC_fb9ee.dir\Debug\cmTC_fb9ee.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_fb9ee.dir\Debug\\" /Fd"cmTC_fb9ee.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue "E:\tmp\protobuf-3.4.0\cmake\b1\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

  Microsoft (R) C/C++ Optimizing Compiler Version 19.11.25506 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_fb9ee.dir\Debug\\" /Fd"cmTC_fb9ee.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue "E:\tmp\protobuf-3.4.0\cmake\b1\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

  CheckIncludeFile.c

  

E:\tmp\protobuf-3.4.0\cmake\b1\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [E:\tmp\protobuf-3.4.0\cmake\b1\CMakeFiles\CMakeTmp\cmTC_fb9ee.vcxproj]

Done Building Project "E:\tmp\protobuf-3.4.0\cmake\b1\CMakeFiles\CMakeTmp\cmTC_fb9ee.vcxproj" (default targets) -- FAILED.

Build FAILED.

"E:\tmp\protobuf-3.4.0\cmake\b1\CMakeFiles\CMakeTmp\cmTC_fb9ee.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  E:\tmp\protobuf-3.4.0\cmake\b1\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [E:\tmp\protobuf-3.4.0\cmake\b1\CMakeFiles\CMakeTmp\cmTC_fb9ee.vcxproj]

    0 Warning(s)

    1 Error(s)

Time Elapsed 00:00:00.86

**Comment by pherl** [comment]
Is this error new in 3.4.0 release? Does it work with 3.3.0?

**Comment by NelsonBilber** [comment]
yes, it works with 3.3.0.

**Comment by NelsonBilber** [comment]
yes, it works with 3.3.0.

**Comment by pherl** [comment]
I searched around the diff between v3.3.0 and v3.4.0 but didn't see anything about pthread. The only change about include/header is https://github.com/google/protobuf/pull/3149/files  I don't have a VC2017 by hand. Could you modify the 3 cmake files locally by removing the ${libprotobuf_lite_includes} and see if it resolves the issue?

**Comment by NelsonBilber** [comment]
Nop. Revert these 3 changes the error remains

**Comment by pherl** [comment]
Can you try if https://github.com/google/protobuf/pull/3565 fixes the issue? Sorry I don't have the environment to debug/fix it myself.

**Comment by NelsonBilber** [comment]
It's fixed.
