### PR TITLE
remove PACKAGE_NAME and REPOSITORY_NAME deprecated usage

### PR DESCRIPTION
**Pull request by ittaiz**
Hi,
We (rules_scala) use this repository as a bazel source repository.
We want to run with bazel 0.13.0 with `--all_incompatible_changes` and fail because of https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#package-name-is-a-function
This PR fixes it.
@dslomov should there be a process to make sure very root projects (like protobuf) support the above flag?
cc @johnynek

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@acozzette  This change is merged in Jun, but only it's not included in 3.6.1. Looks like we have a tag `conformance-build-tag` that contains this fix, but we a fix for another problem is only in 3.6.1.1. Can we have a 3.6.1.2 including both fixes? Otherwise, people will start referencing protobuf at random commit.

**Comment by laurentlb** [comment]
If we have a new release, it should contain every fix to bzl files (it's not the only one, as far as I remember).

**Comment by laurentlb** [comment]
We've been using this repository at head in a few places. So I don't think we're block on this.
@meteorcloudy, do we really need a release?

(I suspect the workaround can wait until 3.7)

**Comment by meteorcloudy** [comment]
At least TensorFlow is not in favor of using protobuf at a random commit, I still think it's worth tagging a 3.6.1.2 release if that's not too much trouble. 

@acozzette Is `conformance-build-tag` also based on `3.6.1`? If so, `3.6.1.2` should contain fixes from both `conformance-build-tag` and `3.6.1.1`. Thanks!

**Comment by acozzette** [comment]
@meteorcloudy I'm not really familiar with `conformance-build-tag` and what that tag is supposed to include. Could you send me a pull request to the `3.6.x` branch with any other fixes you would like to have cherry-picked?

**Comment by meteorcloudy** [comment]
@acozzette I tested the current 3.6.x branch. It works with 0.18.0, 0.19.0, 0.20.0, even with Bazel@HEAD. So please tag a 3.6.1.2 based on that. Thank you!

**Comment by meteorcloudy** [comment]
@acozzette Thank you! I see 3.6.1.2 is out: https://github.com/protocolbuffers/protobuf/releases/tag/v3.6.1.2

@davido Can you help update Gerrit?

**Comment by jin** [comment]
@acozzette could you please promote 3.6.1.2 to a release? The latest release (https://github.com/protocolbuffers/protobuf/releases/latest) seems to be still 3.6.1. Thanks!

**Comment by acozzette** [comment]
@jin We're not planning on doing a full release for 3.6.1.2, because that would involve a lot more work of testing and releasing build artifacts. However, we're starting to work on a full 3.7 release.

**Comment by davido** [comment]
@meteorcloudy Gerrit doesn't depend on protobuf directly. It's a transitive dependency of rules_clsoure. I've updated it to consume protobuf from HEAD. i can update that PR to use v3.6.1.2 instead.

**Comment by davido** [comment]
@meteorcloudy @laurentlb I updated the [PR](https://github.com/bazelbuild/rules_closure/pull/313) for rules_closure to bump protobuf to 3.6.1.2 instead.

**Comment by acozzette** [comment]
We don't have a set date for the 3.7 release, but I'm guessing it should be ready in a month or so.

**Comment by davido** [comment]
@meteorcloudy Apologize, my mistake. Gerrit depends on `protobuf-java`:

```
maven_jar(
    name = "protobuf",
    artifact = "com.google.protobuf:protobuf-java:3.6.1",
    sha1 = "0d06d46ecfd92ec6d0f3b423b4cd81cb38d8b924",
)
```

@acozzette Am I understand correctly, that 3.6.1.2 is not going to be published on Maven Central?

**Comment by davido** [comment]
@acozzette I'm asking because there is complication: We have mismatch of generated code, after bumping Protobuf to recent master and the content of GeneratedMessageV3.class from protobuf-java-3.6.1.jar:

```
1) parseUncheckedWrongProtoType(com.google.gerrit.server.cache.serialize.ProtoCacheSerializersTest)
java.lang.NoSuchMethodError: com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto.emptyIntList()Lcom/google/protobuf/Internal$IntList;
        at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto.<init>(Cache.java:3671)
        at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto.<clinit>(Cache.java:12345)
        at com.google.gerrit.server.cache.serialize.ProtoCacheSerializersTest.parseUncheckedWrongProtoType(ProtoCacheSerializersTest.java:87)
```

This code is generated:

```java
private ChangeNotesStateProto() {
      metaId_ = com.google.protobuf.ByteString.EMPTY;
      pastAssignee_ = emptyIntList();
```

but emptyIntList() doesn't exist in older protobuf-java:3.6.1.jar library.

I will try to downgrade rules-closure to 3.6.2.1 and try again.

**Comment by meteorcloudy** [comment]
@davido Protobuf 3.6.1.2 (Not 3.6.2.1) is expected to have the same protobuf binaries as 3.6.1, so there should be no incompatibility. I think sticking protobuf to 3.6.1.2 is the correct solution, please do that. Thanks!

**Comment by davido** [comment]
@meteorcloudy Thanks for confirming. I've re-opened my PR for rules_closure tp upgrade protobuf to 3.6.1.2 then.

**Comment by davido** [comment]
@acozzette This commit f00e06c95bc117fb2ed0ca56c96041c93039f1fe seems to be lost in recently released 3.6.1.2 version, and only present in v3.5.1, that was used previously in `rules_closure`. Thee this [PR](https://github.com/bazelbuild/rules_closure/pull/318) for more context.

Now, as you mentioned in the commit message, closure tests are failing.

We have two options:

1. Create 3.6.1.3 with f00e06c95bc117fb2ed0ca56c96041c93039f1fe cherry-picked
2. update rules_closure to add a patch and t get rid of this block in js/binary/utils.js:

```javascript
+  if (data.constructor === Buffer) {
+    return /** @type {!Uint8Array} */(new Uint8Array(data));
+  }
+
```

WDYT?

**Comment by davido** [comment]
> 2. Update rules_closure to add a patch and to get rid of this block in js/binary/utils.js

Done in: [1].

[1] https://github.com/bazelbuild/rules_closure/pull/319

**Comment by davido** [comment]
@acozzette 

> 1. Create 3.6.1.3 with f00e06c cherry-picked

I've cherry-picked f00e06c in this PR: [1]. Can you help to merge it and create 3.6.1.3 from the tip of 3.6.x branch? Then we wouldn't need rules_closure patch. Thanks in advance!

[1] https://github.com/protocolbuffers/protobuf/pull/5433

**Comment by jovany-wang** [comment]
+1
