### ISSUE TITLE
Python cpp implementation doesn't build with python 2.6

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#758]
Failing travis test: https://travis-ci.org/google/protobuf/jobs/77443313

Error message:
```
google/protobuf/pyext/message.cc:1783:14: error: ‘PyFloat_STR_PRECISION’ was not declared in this scope
```
This symbol is introduced in a down-integration commit (i.e., first added in our internal code base).

**Comment by haberman** [comment]
Looking into this.

I'm not sure this needs to hold up the release. Python 2.6 is extremely old and we only decided to support it because RedHat might still be distributing it. If only pure-Python worked for this beta release on Python 2.6, I think that would be acceptable.

**Comment by haberman** [comment]
I think I can fix this bug relatively easily. Do you want to send a PR?

**Comment by xfxyjwf** [comment]
We are releasing beta-1 without this. Let's fix it before merging beta-1 to master though.

**Comment by QuLogic** [comment]
Just as a [side note](http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html).
