### ISSUE TITLE
compile on RHEL 6.6 with gcc 4.4.7

### ISSUE THREAD

**Issue by kamaaina** [google/protobuf#3557]
i tried to compile 3.2.x and am getting errors with metadata.h

```
In file included from ./google/protobuf/any.pb.h:26,
                 from google/protobuf/any.pb.cc:5:
                 ./google/protobuf/metadata.h: In constructor ‘google::protobuf::internal::InternalMetadataWithArena::InternalMetadataWithArena(google::protobuf::Arena*)’:
                 ./google/protobuf/metadata.h:175: error: class ‘google::protobuf::internal::InternalMetadataWithArena’ does not have any field named ‘InternalMetadataWithArenaBase’
                 ./google/protobuf/metadata.h: In constructor ‘google::protobuf::internal::InternalMetadataWithArenaLite::InternalMetadataWithArenaLite(google::protobuf::Arena*)’:
                 ./google/protobuf/metadata.h:204: error: class ‘google::protobuf::internal::InternalMetadataWithArenaLite’ does not have any field named ‘InternalMetadataWithArenaBase’
```

i saw a post about a fix, but it applied to 3.3.x [here](https://github.com/google/protobuf/pull/2599) and other similar ones. however, i tried to apply it as well (but 3.3.x has different files). long story short, still have this problem... please help

**Comment by pherl** [comment]
Does it fix by adding the explicit template parameter in https://github.com/google/protobuf/blob/3.2.x/src/google/protobuf/metadata.h#L175 and Line 204? The meatadata.h file looks the same on 3.2.x branch to me.
