### ISSUE TITLE
rubygem google-protobuf-3.5.1.2.gem fails to compile with ruby 2.5

### ISSUE THREAD

**Issue by frispete** [google/protobuf#4809]
**What version of protobuf and what language are you using?**
Version: v3.5.1.2
Language: Ruby
https://rubygems.org/downloads/google-protobuf-3.5.1.2.gem
**What operating system (Linux, Windows, ...) and version?**
openSUSE Linux Tumbleweed
**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 8.1.1
ruby 2.5.0
All involved versions can be seen in the build log download (link below)
**What did you do?**
Build on OBS: https://build.opensuse.org/package/live_build_log/home:frispete:GitLab/rubygem-google-protobuf/openSUSE_Tumbleweed/x86_64
**Reproduce**
Install Tumbleweed
```
osc co home:frispete:GitLab rubygem-google-protobuf
cd home\:frispete\:GitLab/rubygem-google-protobuf
osc build openSUSE_Tumbleweed x86_64 rubygem-google-protobuf.spec
```
results in:
```
[   23s] compiling storage.c
[   23s] storage.c: In function ‘native_slot_set_value_and_case’:
[   23s] storage.c:180:17: warning: initialization of ‘long unsigned int’ from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
[   23s]          value = rb_funcall(value, rb_intern("to_s"), 0, NULL);
[   23s]                  ^~~~~~~~~~
[   23s] storage.c:180:17: note: (near initialization for ‘rb_funcall_args[0]’)
[   23s] storage.c:210:17: warning: initialization of ‘long unsigned int’ from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
[   23s]          value = rb_funcall(value, rb_intern("to_sym"), 0, NULL);
[   23s]                  ^~~~~~~~~~
[   23s] storage.c:210:17: note: (near initialization for ‘rb_funcall_args[0]’)
[   23s] In file included from protobuf.h:34,
[   23s]                  from storage.c:31:
[   23s] /usr/include/ruby-2.5.0/ruby/ruby.h:1775:3: error: call to ‘rb_varargs_bad_length’ declared with attribute error:  argument length doesn't match
[   23s]    rb_varargs_bad_length(argc, vargc)), \
[   23s]    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   23s] /usr/include/ruby-2.5.0/ruby/ruby.h:2470:6: note: in expansion of macro ‘rb_varargs_argc_check’
[   23s]       rb_varargs_argc_check(rb_funcall_argc, rb_funcall_nargs), \
[   23s]       ^~~~~~~~~~~~~~~~~~~~~
[   23s] storage.c:180:17: note: in expansion of macro ‘rb_funcall’
[   23s]          value = rb_funcall(value, rb_intern("to_s"), 0, NULL);
[   23s]                  ^~~~~~~~~~
[   23s] /usr/include/ruby-2.5.0/ruby/ruby.h:1775:3: error: call to ‘rb_varargs_bad_length’ declared with attribute error:  argument length doesn't match
[   23s]    rb_varargs_bad_length(argc, vargc)), \
[   23s]    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   23s] /usr/include/ruby-2.5.0/ruby/ruby.h:2470:6: note: in expansion of macro ‘rb_varargs_argc_check’
[   23s]       rb_varargs_argc_check(rb_funcall_argc, rb_funcall_nargs), \
[   23s]       ^~~~~~~~~~~~~~~~~~~~~
[   23s] storage.c:210:17: note: in expansion of macro ‘rb_funcall’
[   23s]          value = rb_funcall(value, rb_intern("to_sym"), 0, NULL);
[   23s]                  ^~~~~~~~~~
[   23s] make: *** [Makefile:242: storage.o] Error 1
[   23s] ERROR:  Error installing /home/abuild/rpmbuild/SOURCES/google-protobuf-3.5.1.2.gem:
[   23s]        ERROR: Failed to build gem native extension.
[   23s] 
[   23s]     Building has failed. See above output for more information on the failure.
[   23s] make failed, exit code 2
[   23s] 
```
Obviously, the signature of `rb_varargs_bad_length` changed with ruby 2.5.

**Comment by TeBoring** [comment]
Does 3.6.0 release fix the problem?

**Comment by TeBoring** [comment]
I think this is broken by https://github.com/google/protobuf/pull/3627

**Comment by TeBoring** [comment]
https://bugs.ruby-lang.org/issues/14425

**Comment by TeBoring** [comment]
@frispete I think ruby has change in later release. Could you use newer version of ruby?

**Comment by zanker** [comment]
@TeBoring What are you looking for? Happy to take a look, but seems like it's mostly a Ruby bug that they've fixed already.

**Comment by TeBoring** [comment]
Fixed in #4829
