### ISSUE TITLE
install php extension failed

### ISSUE THREAD

**Issue by sylarXu** [google/protobuf#1673]
protobuf version is 3.0.0
php version is 7.0.2
/bin/sh /usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/libtool --mode=compile cc  -I. -I/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf -DPHP_ATOM_INC -I/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/include -I/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/main -I/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.c -o protobuf.lo 
 cc -I. -I/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf -DPHP_ATOM_INC -I/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/include -I/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/main -I/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.c  -fPIC -DPIC -o .libs/protobuf.o
In file included from /usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.c:1:0:
/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.h:182:1: error: unknown type name ‘zend_object_value’
 zend_object_value descriptor_pool_create(zend_class_entry *ce TSRMLS_DC);
 ^
/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.h:190:1: error: unknown type name ‘zend_object_value’
 zend_object_value descriptor_create(zend_class_entry *ce TSRMLS_DC);
 ^
/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.h:197:1: error: unknown type name ‘zend_object_value’
 zend_object_value message_builder_context_create(
 ^
/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.c: In function ‘add_def_obj’:
/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.c:20:55: error: macro "zend_hash_index_update" passed 5 arguments, but takes just 3
                          &value, sizeof(zval*), &pDest);
                                                       ^
/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.c:19:3: error: ‘zend_hash_index_update’ undeclared (first use in this function)
   zend_hash_index_update(&PROTOBUF_G(upb_def_to_php_obj_map), (zend_ulong)def,
   ^
/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.c:19:3: note: each undeclared identifier is reported only once for each function it appears in
/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.c: In function ‘get_def_obj’:
/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.c:26:28: error: too many arguments to function ‘zend_hash_index_find’
                            &value) == FAILURE) {
                            ^
In file included from /usr/local/php/include/php/Zend/zend.h:36:0,
                 from /usr/local/php/include/php/main/php.h:35,
                 from /usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.h:4,
                 from /usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.c:1:
/usr/local/php/include/php/Zend/zend_hash.h:156:30: note: declared here
 ZEND_API zval* ZEND_FASTCALL zend_hash_index_find(const HashTable *ht, zend_ulong h);
                              ^
/usr/local/src/protobuf-3.0.0-beta-3/php/ext/google/protobuf/protobuf.c:26:36: warning: comparison between pointer and integer [enabled by default]
                            &value) == FAILURE) {
                                    ^
make: *** [protobuf.lo] Error 1

**Comment by xfxyjwf** [comment]
I believe the php implementation is not ready to use yet (not even in alpha). @TeBoring

**Comment by TeBoring** [comment]
This is not ready yet. Thanks for trying that.

**Comment by thinkerou** [comment]
You should use php5.x not php7 in addition to your errors.

**Comment by sylarXu** [comment]
@thinkerou thank you for your help.it works well in php5.6

**Comment by dinoxxx** [comment]
@TeBoring
