### PR TITLE
Update file list to include the missing extension lite file.

### LINKED ISSUE #1410: Commit 3b3c8abb9635eb3ea078a821a99c9ef29d66dff7 broke bazel build with sandboxing
Reposting from https://github.com/google/protobuf/commit/3b3c8abb9635eb3ea078a821a99c9ef29d66dff7

We are issuing a new release so traging the breakage we see on ci.bazel.io

See http://ci.bazel.io/job/protobuf/136/ (bisected to find the culprit).

The exact log:
```
$ bazel build //:protoc
INFO: Found 1 target...
ERROR: /usr/local/google/home/dmarting/toto/protobuf/BUILD:271:1: Linking of rule '//:protoc' failed: namespace-sandbox failed: error executing command <user_home>/.cache/bazel/_bazel_dmarting/c28d9280fb33934092856a1adca4fe91/protobuf/_bin/namespace-sandbox ... (remaining 13 argument(s) skipped).
bazel-out/local_linux-fastbuild/bin/libprotoc_lib.a(java_generator_factory.pic.o): In function `google::protobuf::compiler::java::ImmutableGeneratorFactory::NewExtensionGenerator(google::protobuf::FieldDescriptor const*) const':
java_generator_factory.cc:(.text+0x265): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::ImmutableExtensionLiteGenerator(google::protobuf::FieldDescriptor const*, google::protobuf::compiler::java::Context*)'
bazel-out/local_linux-fastbuild/bin/libprotoc_lib.a(java_message_lite.pic.o): In function `google::protobuf::compiler::java::ImmutableMessageLiteGenerator::Generate(google::protobuf::io::Printer*)':
java_message_lite.cc:(.text+0x1b82): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::ImmutableExtensionLiteGenerator(google::protobuf::FieldDescriptor const*, google::protobuf::compiler::java::Context*)'
java_message_lite.cc:(.text+0x1b9b): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::Generate(google::protobuf::io::Printer*)'
java_message_lite.cc:(.text+0x1baa): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::~ImmutableExtensionLiteGenerator()'
java_message_lite.cc:(.text+0x1f41): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::~ImmutableExtensionLiteGenerator()'
bazel-out/local_linux-fastbuild/bin/libprotoc_lib.a(java_message_lite.pic.o): In function `google::protobuf::compiler::java::ImmutableMessageLiteGenerator::GenerateExtensionRegistrationCode(google::protobuf::io::Printer*)':
java_message_lite.cc:(.text+0x394e): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::ImmutableExtensionLiteGenerator(google::protobuf::FieldDescriptor const*, google::protobuf::compiler::java::Context*)'
java_message_lite.cc:(.text+0x3961): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::GenerateRegistrationCode(google::protobuf::io::Printer*)'
java_message_lite.cc:(.text+0x396d): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::~ImmutableExtensionLiteGenerator()'
java_message_lite.cc:(.text+0x3a14): undefined reference to `google::protobuf::compiler::java::ImmutableExtensionLiteGenerator::~ImmutableExtensionLiteGenerator()'
collect2: error: ld returned 1 exit status
Target //:protoc failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 28.883s, Critical Path: 27.78s
```

### PR DESCRIPTION
**Pull request by pherl**
Fixes #1410

### CODE REVIEW

**Comment by xfxyjwf** [comment]
LGTM
