### ISSUE TITLE
compilation issue with bazel/gcc on ubuntu 14.04

### ISSUE THREAD

**Issue by mzhaom** [google/protobuf#715]
INFO: From Compiling third_party/protobuf/upstream/src/google/protobuf/util/internal/utility.cc:
In file included from third_party/protobuf/upstream/src/google/protobuf/util/internal/utility.cc:44:0:
third_party/protobuf/upstream/src/google/protobuf/stubs/mathlimits.h: In static member function 'static bool google::protobuf::MathLimits<double>::IsFinite(google::protobuf::MathLimits<double>::Type)':
third_party/protobuf/upstream/src/google/protobuf/stubs/mathlimits.h:269:1: error: call of overloaded 'isinf(const Type&)' is ambiguous
 DECL_FP_LIMITS(double, DBL)
 ^
third_party/protobuf/upstream/src/google/protobuf/stubs/mathlimits.h:269:1: note: candidates are:
In file included from /usr/include/features.h:374:0,
                 from /usr/include/x86_64-linux-gnu/c++/4.8/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/4.8/bits/c++config.h:426,
                 from /usr/include/c++/4.8/bits/stl_algobase.h:59,
                 from /usr/include/c++/4.8/memory:62,
                 from third_party/protobuf/upstream/src/google/protobuf/util/internal/utility.h:34,
                 from third_party/protobuf/upstream/src/google/protobuf/util/internal/utility.cc:31:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:201:1: note: int isinf(double)
 __MATHDECL_1 (int,isinf,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from third_party/protobuf/upstream/src/google/protobuf/util/internal/utility.cc:33:0:
/usr/include/c++/4.8/cmath:608:3: note: constexpr bool std::isinf(long double)
   isinf(long double __x)
   ^
/usr/include/c++/4.8/cmath:604:3: note: constexpr bool std::isinf(double)
   isinf(double __x)
   ^
/usr/include/c++/4.8/cmath:600:3: note: constexpr bool std::isinf(float)
   isinf(float __x)
   ^

**Comment by mzhaom** [comment]
Comment out "src/google/protobuf/util/internal/utility.cc" from the BUILD solves this problem.

**Comment by nsuke** [comment]
Apparently, bazel puts "-std=c++0x" to compiler flags, and protobuf does not build on gcc 4.8 with C++11 right now (#674 fixes latter).

Strangely, forcing older standard by

    bazel bulid --cxxopts=-std=c++03 :protobuf

didn't work and failed with a different error (same result for -std=c++98).

    src/google/protobuf/stubs/stringprintf.cc:65:24: error: 'va_copy' was not declared in this scope

**Comment by pherl** [comment]
Merged in #674
