### ISSUE TITLE
Names of namespaces clash (C++)

### ISSUE THREAD

**Issue by joto** [google/protobuf#3902]
It seems protoc generates namespaces based on the name of the `.proto` file in the pb.h/pb.cc files. In my case there is a file `testcase.proto` and a namespace `protobuf_testcase_2eproto`. Problem is: I have multiple files with the same name in different directories which leads to "duplicate symbol" errors from the linker.

Note that this is not the namespace based on the `package` setting in the `.proto` file, I have different names for those.

This used to work in 3.0 and doesn't work any more with 3.5. I don't know where exactly the problem was introduced.

**Comment by pherl** [comment]
Thanks for reporting and sorry for the breakage. It will be fixed in the next minor release.

**Comment by gerben-s** [comment]
So the descriptor pool already indexes descriptors on the filename. Having multiple files with the same name was already broken. Although it might not have triggered as this happens on calls to reflection.

In a sense this improves things. What used to be a hidden runtime problem, now becomes a static linker error.
