### PR TITLE
Adding Release_CompareAndSwap 64-bit variant

### PR DESCRIPTION
**Pull request by Nayana-ibm**
While building Protobuf v3.5.0 (latest stable) facing an issue:  undefined reference to `google::protobuf::internal::Release_CompareAndSwap(long volatile*, long, long)' 

Need to add 64-bit version for function : Release_CompareAndSwap

 I had already raised an issue here : https://github.com/google/protobuf/issues/3937

### CODE REVIEW

**Comment by xfxyjwf** [comment]
Thanks for the patch!

**Comment by xfxyjwf** [comment]
ok to test

**Comment by Nayana-ibm** [comment]
When this patch can be merged?

**Comment by rc-matthew-l-weber** [comment]
Could this be pulled into the 3.5.x branch (wasn't sure if 3.5.1.1 is still in development)?  We've observed a similar failure with sparc as part of a buildroot build using the 3.5.1 release and would like to version bump vs carrying a patch (http://autobuild.buildroot.net/results/5480a6087a5a782505cec88f797116d8679df3ac/build-end.log).

**Comment by Nayana-ibm** [comment]
@xfxyjwf When this will get tagged? which version?

**Comment by rc-matthew-l-weber** [comment]
@xfxyjwf   what's the release cycle timeline for protobuf?
