### ISSUE TITLE
Cross compile error with 3.0 for powerpc

### ISSUE THREAD

**Issue by zhengh81** [google/protobuf#2427]
Hi,

I'm trying to cross compile protobuf (3.0) for ppc and getting following errors.
Is there any known issues with cross compiling since I'm able to cross compile for arm successfully?

1. configure
./configure --host=i386-linux CC=/fullpath/to/mytoolchain/bin/powerpc-405-linux-gnu-gcc CXX=/fullpath/to/mytoolchain/bin/powerpc-405-linux-gnu-g++ --with-protoc=/usr/local/bin/protoc --prefix=$(pwd)/powerpc

Quick question, is setting i386-linux for host correct?

2. make
libtool: compile:  /fullpath/to/mytoolchain/bin/powerpc-405-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I.. -pthread -DHAVE_PTHREAD=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/dynamic_message.lo -MD -MP -MF google/protobuf/.deps/dynamic_message.Tpo -c google/protobuf/dynamic_message.cc  -fPIC -DPIC -o google/protobuf/.libs/dynamic_message.o
In file included from google/protobuf/dynamic_message.cc:80:

./google/protobuf/map_field.h: In member function 'void google::protobuf::internal::MapField<Key, T, key_wire_type, value_wire_type, default_enum_value>::Swap(google::protobuf::internal::MapFieldLite<Key, T, kKeyFieldType, kValueFieldType, default_enum_value>*)':
./google/protobuf/map_field.h:139: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:342: error: from this location
./google/protobuf/map_field.h:150: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::state_'
./google/protobuf/map_field_inl.h:344: error: from this location
./google/protobuf/map_field.h: In member function 'void google::protobuf::internal::MapField<Key, T, key_wire_type, value_wire_type, default_enum_value>::SetEntryDescriptor(const google::protobuf::Descriptor**)':
./google/protobuf/map_field.h:145: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::entry_descriptor_'
./google/protobuf/map_field_inl.h:355: error: from this location
./google/protobuf/map_field.h: In member function 'void google::protobuf::internal::MapField<Key, T, key_wire_type, value_wire_type, default_enum_value>::SetAssignDescriptorCallback(void (*)())':
./google/protobuf/map_field.h:146: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::assign_descriptor_callback_'
./google/protobuf/map_field_inl.h:365: error: from this location
./google/protobuf/map_field.h: In member function 'void google::protobuf::internal::MapField<Key, T, key_wire_type, value_wire_type, default_enum_value>::SyncRepeatedFieldWithMapNoLock() const':
./google/protobuf/map_field.h:139: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:395: error: from this location
./google/protobuf/map_field.h:138: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::arena_'
./google/protobuf/map_field_inl.h:396: error: from this location
./google/protobuf/map_field.h:139: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:397: error: from this location
./google/protobuf/map_field.h:139: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:399: error: from this location
./google/protobuf/map_field.h:138: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::arena_'
./google/protobuf/map_field_inl.h:401: error: from this location
./google/protobuf/map_field.h:139: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:407: error: from this location
./google/protobuf/map_field.h:138: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::arena_'
./google/protobuf/map_field_inl.h:416: error: from this location
./google/protobuf/map_field.h: In member function 'void google::protobuf::internal::MapField<Key, T, key_wire_type, value_wire_type, default_enum_value>::SyncMapWithRepeatedFieldNoLock() const':
./google/protobuf/map_field.h:139: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:433: error: from this location
./google/protobuf/map_field.h:139: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:434: error: from this location
./google/protobuf/map_field.h: In member function 'int google::protobuf::internal::MapField<Key, T, key_wire_type, value_wire_type, default_enum_value>::SpaceUsedExcludingSelfNoLock() const':
./google/protobuf/map_field.h:139: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:455: error: from this location
./google/protobuf/map_field.h:139: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:456: error: from this location
./google/protobuf/map_field.h: In member function 'void google::protobuf::internal::MapField<Key, T, key_wire_type, value_wire_type, default_enum_value>::InitDefaultEntryOnce() const':
./google/protobuf/map_field.h:145: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::entry_descriptor_'
./google/protobuf/map_field_inl.h:478: error: from this location
./google/protobuf/map_field.h:145: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::entry_descriptor_'
./google/protobuf/map_field_inl.h:481: error: from this location
make[3]: *** [google/protobuf/dynamic_message.lo] Error 1

Do I need to try latest release?

Any information on similar issues will be greatly appreciated.

**Comment by zhengh81** [comment]
Issue resolved after upgrading gcc from 4.3 to 5.2. (It may work with 4.7 above gcc)
