### ISSUE TITLE
VS2008 build issue with protobuf 3.5.0

### ISSUE THREAD

**Issue by jakirkham** [google/protobuf#4064]
Ran into the following issue when trying to build `protobuf` 3.5.0 where `map::at` was used. The [`map::at` method only exists in C++11]( http://en.cppreference.com/w/cpp/container/map/at ). As such it cannot compile with a non-C++11 compiler like VS2008.

```
C:\bld\protobuf_1513642428254\work\protobuf-3.5.0\src\google\protobuf\util\field_mask_util.cc(377) : error C2039: 'at' : is not a member of 'std::map<_Kty,_Ty>'
        with
        [
            _Kty=std::string,
            _Ty=google::protobuf::util::`anonymous-namespace'::FieldMaskTree::Node *
        ]
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
```

ref: https://ci.appveyor.com/project/conda-forge/protobuf-feedstock/build/job/o85bad6hfjhvyxvu

**Comment by xfxyjwf** [comment]
We will release 3.5.1 very soon. Could you help make a pull request to fix this in the 3.5.x branch?

@pherl is working on 3.5.1 release.

**Comment by jakirkham** [comment]
PR ( https://github.com/google/protobuf/pull/4074 ) fixed this issue.

**Comment by jakirkham** [comment]
Should add that when trying to build `protobuf` with that patch ran into issue ( https://github.com/google/protobuf/issues/4075 ).
