### ISSUE TITLE
NVCC 7.0 does not work with the most recent protobuf version

### ISSUE THREAD

**Issue by Yangqing** [google/protobuf#787]
Specifically, after the introduction of is_destructor_skippable, NVCC 7.0 now fails, complaining that there is conflict in type definition. I traced the problem down to an internal nvcc problem, and reported a bug to nvidia. However, I am curious if we can simplify the current is_destructor_skippable mechanism to go around the nvcc compiler issue, since the nvcc bugfix may take a while...

I documented the error in detail in the following google doc:

https://docs.google.com/document/d/1koMK7Yhm_VdgsBjYLttbqTYNj6_mnN1PBVfoMjhjDLY/edit#

**Comment by xfxyjwf** [comment]
Impressive analysis!

I was actually thinking about fixing the is_destructor_skippable/is_arena_constructable traits to more like the standard type traits. Standard type traits inherits from std::integral_constant but our is_destructor_skippable/is_arena_construtable traits are not. A more noticeable difference is that the member constant value is defined to be of type std::integral_constant while in standard type traits it's just bool.

What I have in mind is something like this:
```cpp
struct Helper {
  template<typename U>
  static char DestructorSkippable(
      const typename U::DestructorSkippable_*);
  template<typename U>
  static double DestructorSkippable(...);
};
template<typename T>
struct is_destructor_skippable
    : public std::integral_constant<bool,
          sizeof(Helper::DestructorSkippable<const T>(static_cast<const T*>(0))) ==
          sizeof(char) || has_trivial_destructor<T>::value> {
};
```

Could you check if it works with NVCC 7.0?

**Comment by Yangqing** [comment]
Thanks @xfxyjwf! Would you mind sending a patch that I can apply and test against nvcc?

**Comment by Yangqing** [comment]
I did a quick hack and it turns out that the following code works:

```c++
  template<typename T>
  struct is_destructor_skippable {
    template<typename U>
    static char DestructorSkippable(
        const typename U::DestructorSkippable_*);
    template<typename U>
    static double DestructorSkippable(...);

    static const bool skippable =
          sizeof(DestructorSkippable<const T>(static_cast<const T*>(0))) ==
          sizeof(char) || google::protobuf::internal::has_trivial_destructor<T>::value == true;

    // This will resolve to either google::protobuf::internal::true_type or google::protobuf::internal::false_type.
    typedef google::protobuf::internal::integral_constant<bool, skippable> type;
    static const type value;
  };
```

Nothing really got changed, I just split the long argument into a separate static const variable. Would you like me to send a PR for this?

**Comment by xfxyjwf** [comment]
Yes, please send a PR for this.

I also had an experimental change to make the type traits more like standard ones. Could you help verify if it works with NVCC 7.0?
https://github.com/xfxyjwf/protobuf/commit/494716a682ef854168e92231a3cdcc89d587d9b9

My change affects public API and I plan to make it in our internal code base first. We can use your change for the time being in this github repo.

**Comment by Yangqing** [comment]
Thanks @xfxyjwf - your change works with nvcc 7.0. I tested with the same simple program above.

**Comment by shenrb2015** [comment]
HI, I encounter a problem very similar with this issue, but it has a little different, the error messages like this:

/usr/local/include/google/protobuf/arena.h:920: error: conflicting declaration 'const google::protobuf::internal::integral_constant<bool, google::protobuf::Arena::is_destructor_skippable::raw_skippable_value> google::protobuf::Arena::is_destructor_skippable<T>::value'
/usr/local/include/google/protobuf/arena.h:600: error: 'google::protobuf::Arena::is_destructor_skippable<T>::value' has a previous declaration as 'const google::protobuf::internal::integral_constant<bool, google::protobuf::Arena::is_destructor_skippable<T>::raw_skippable_value> google::protobuf::Arena::is_destructor_skippable<T>::value'
/usr/local/include/google/protobuf/arena.h:920: error: declaration of 'const google::protobuf::internal::integral_constant<bool, google::protobuf::Arena::is_destructor_skippable<T>::raw_skippable_value> google::protobuf::Arena::is_destructor_skippable<T>::value' outside of class is not definition
make: *** [.build_release/cuda/src/caffe/layers/prelu_layer.o] Error 1

I have checked the line nearly 600 in the file /usr/local/include/google/protobuf/arena.h, it looks be fixed as you mentioned, the related code like this:

 template<typename T>
  struct is_destructor_skippable {
    template<typename U>
    static char DestructorSkippable(
        const typename U::DestructorSkippable_*);
    template<typename U>
    static double DestructorSkippable(...);

    // The raw_skippable_value const bool variable is separated from the typedef
    // line below as a work-around of an NVCC 7.0 (and earlier) compiler bug.
    static const bool raw_skippable_value =
          sizeof(DestructorSkippable<const T>(static_cast<const T*>(0))) ==
          sizeof(char) || google::protobuf::internal::has_trivial_destructor<T>::value == true;
    // This will resolve to either google::protobuf::internal::true_type or  
    //  google::protobuf::internal::false_type.
    typedef google::protobuf::internal::integral_constant<bool, raw_skippable_value> type;
    static const type value;
  };

The problem may be caused by protobuf;
please help, thanks a lot!

**Comment by kyuusaku** [comment]
Hi, @shenrb2015 I met the same error. Did you fix it?

**Comment by shenrb2015** [comment]
HI,@kyuusaku
I don't find methods to fix this problem, maybe the previous installation lacked some shared libraries;
I reinstalled the required packages with source codes, and the problem was not present.

**Comment by xfxyjwf** [comment]
Fixed by https://github.com/google/protobuf/pull/1025
