### ISSUE TITLE
PHP: Unable to build v3.3.0/master extension with PHP 7.*

### ISSUE THREAD

**Issue by christophermancini** [google/protobuf#3101]
I failed to build the v3.3.0 or master extension with PHP 7.0 or 7.1 on Mac OS X or Ubuntu 14.04. The error I encountered is consistent regardless of the version / environment:

```
libtool: compile:  cc -I. -I/home/vagrant/code/protobuf/php/ext/google/protobuf -DPHP_ATOM_INC -I/home/vagrant/code/protobuf/php/ext/google/protobuf/include -I/home/vagrant/code/protobuf/php/ext/google/protobuf/main -I/home/vagrant/code/protobuf/php/ext/google/protobuf -I/usr/include/php/20160303 -I/usr/include/php/20160303/main -I/usr/include/php/20160303/TSRM -I/usr/include/php/20160303/Zend -I/usr/include/php/20160303/ext -I/usr/include/php/20160303/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/vagrant/code/protobuf/php/ext/google/protobuf/message.c  -fPIC -DPIC -o .libs/message.o
In file included from /usr/include/php/20160303/Zend/zend_globals.h:28:0,
                 from /usr/include/php/20160303/Zend/zend_compile.h:688,
                 from /usr/include/php/20160303/Zend/zend_modules.h:26,
                 from /usr/include/php/20160303/Zend/zend_API.h:27,
                 from /usr/include/php/20160303/main/php.h:40,
                 from /home/vagrant/code/protobuf/php/ext/google/protobuf/message.c:31:
/home/vagrant/code/protobuf/php/ext/google/protobuf/message.c: In function 'message_set_property':
/usr/include/php/20160303/Zend/zend_globals_macros.h:46:33: error: 'zend_executor_globals' has no member named 'scope'
 # define EG(v) (executor_globals.v)
                                 ^
/home/vagrant/code/protobuf/php/ext/google/protobuf/message.c:119:28: note: in expansion of macro 'EG'
   if (Z_OBJCE_P(object) != EG(scope)) {
                            ^
/home/vagrant/code/protobuf/php/ext/google/protobuf/message.c: In function 'message_get_property':
/usr/include/php/20160303/Zend/zend_globals_macros.h:46:33: error: 'zend_executor_globals' has no member named 'scope'
 # define EG(v) (executor_globals.v)
                                 ^
/home/vagrant/code/protobuf/php/ext/google/protobuf/message.c:149:28: note: in expansion of macro 'EG'
   if (Z_OBJCE_P(object) != EG(scope)) {
                            ^
make: *** [message.lo] Error 1
```

**Comment by TeBoring** [comment]
Fixed in 3.3.1 release. pecl package hasn't been uploaded.

**Comment by TeBoring** [comment]
Which 7.0 php are you using? I don't think 7.0 has such issue.

**Comment by christophermancini** [comment]
@TeBoring I think you are right, that it works fine in PHP7.0. I had both installed and I think a symlink somewhere caused the extension to use PHP7.1 for building. Master branch is working on PHP7.0.
